#!/bin/sh

docker pull mariadb

mkdir -p files

mvn -f ../pom/pap/pom.xml clean package
mvn -f ../pom/pdp/pom.xml clean package

cp ../pom/pap/target/keypassPAP-?.?.?.jar ./pap/keypassPAP.jar
cp ../pom/pdp/target/keypassPDP-?.?.?.jar ./pdp/keypassPDP.jar

docker build --rm -t keypasspap pap
docker build --rm -t keypasspdp pdp
