#!/bin/sh

set -e

#build jar files
mvn -f ../pom/pap/pom.xml clean package
mvn -f ../pom/pdp/pom.xml clean package

# Copy Jar files
cp ../pom/pap/target/keypassPAP-?.?.?.jar ./pap/keypassPAP.jar
cp ../pom/pdp/target/keypassPDP-?.?.?.jar ./pdp/keypassPDP.jar

# Copy wait for it script
cp ./files/wait-for-it.sh ./pap/
cp ./files/wait-for-it.sh ./pdp/


rm -rf env

virtualenv env --python=python3

. env/bin/activate

pip install PyYAML \
            git+https://github.com/tantSinnister/rework.git@v0.0.2 \
            git+https://github.com/tantSinnister/psst.git@v0.0.2 \
            git+https://github.com/tantSinnister/bob_cert_builder.git@v0.0.2

deactivate


./init

#Build images
docker-compose build
