#!/bin/sh

docker pull mariadb

mkdir -p files

mvn -f ../pom/pap/pom.xml clean package
mvn -f ../pom/pdp/pom.xml clean package

cp ../pom/pap/target/keypassPAP-0.4.2.jar ./pap/
cp ../pom/pdp/target/keypassPDP-0.4.2.jar ./pdp/

docker build --rm -t keypasspap pap
docker build --rm -t keypasspdp pdp
