version: '2'
services:
    amdb:
      image: mariadb
      expose:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: keypass
      volumes:
          - ./volumes/db/:/docker-entrypoint-initdb.d:ro

    ampap:
      build: ./pap/
      command: ["/opt/keypass/start"]
      entrypoint: ["/opt/keypass/wait-for-it.sh", "amdb:3306", "--"]
      links:
        - amdb
      depends_on:
        - amdb
      ports:
        - "8443:8443"
      volumes:
          - ./volumes/pap/:/opt/keypass/conf:ro

    ampdp:
      build: ./pdp/
      command: ["/opt/keypass/start"]
      entrypoint: ["/opt/keypass/wait-for-it.sh", "amdb:3306", "--"]
      links:
        - amdb
      depends_on:
        - amdb
      ports:
        - "8444:8443"
      volumes:
          - ./volumes/pdp/:/opt/keypass/conf:ro

