#!/bin/sh

set -e

. env/bin/activate


mkdir -p -- ./volumes/pap/
mkdir -p -- ./volumes/pdp/
mkdir -p -- ./volumes/db/

printf "Init Certificates and passwords and creating config files.\n"
printf '{ "psst": %s, "bob": %s }\n' "$(psst config.yml)" "$(bob config.yml)" | rework config.yml
cp ./certs/AMpap/AMpap.keystore.jks ./volumes/pap/key.store
cp ./certs/AMpdp/AMpdp.keystore.jks ./volumes/pdp/key.store

printf "Done.\n"
