#!/bin/sh

database_root_pw=$(jq --raw-output '.psst.database_root_pw' init.json)


printf "Start database container. \n"
docker run --name AMdb -e MYSQL_ROOT_PASSWORD="$database_root_pw" \
    -v "$PWD"/volumes/db:/docker-entrypoint-initdb.d:ro \
    -d  mariadb 
printf "Root password for Database: %s\n" "$database_root_pw"
printf "Maybe you should write it down somewhere!\n"


printf "Wait for database to start ."

until printf ""| docker exec -i AMdb mysql -u'root' -p"$database_root_pw" > /dev/null 2>&1; do
    printf "."
    sleep 1
done
printf " done.\n"
printf "Starting PAP and PDP containers. \n"
docker run --restart=always --name AMpap --link=AMdb:db \
    -v "$PWD"/volumes/pap:/opt/keypass/conf:ro \
    -h AMpap -p 8443:8443 -d keypasspap 
docker run --restart=always --name AMpdp --link=AMdb:db \
    -v "$PWD"/volumes/pdp:/opt/keypass/conf:ro \
    -h AMpdp -p 8444:8443 -d keypasspdp
